
  project_name: "Curculionidae of the World Online"
  project_citation: "Curculionidae of the World Online. TaxonPages"
  project_url: http://catalog.curculionoidea.org/
  project_authors: "Yunakov, N., Girón Duque, J.C., Brown, S., Jilg, J., Meregalli, M., Anderson, R.S., del Río, M.G., Rincón, J., Cortés-Hernández, K., Cabras, A. (2026)."
  og_image: "/public/images/og_image.png"
